function change(argument) {
	if (argument == 'index') {
		document.open
		document.write(`<!DOCTYPE html><html><head><link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet"><link rel="stylesheet" type="text/css" href="css/style.css"><title>Gerador de provas</title><meta charset="UTF-8"></head><body onload="resetad();"><center><div id="main1"><h1>Gerador de provas - Inicio</h1><label>Quantidade de questões</label><br><input type="number" name="q1" min="1" id="q1" value="1" required="true"><br><label>Quantidade de alternativas</label><br><input type="number" name="q2" min="2" id="q2" value="2" required="true"><br><label>Variedade de provas</label><br><input type="number" name="q3" min="1" id="q3" value="1" required="true"><br><label>Questões extras</label><br><input type="number" name="q4" min="0" id="q4" value="0" required="true"><br><br><button class="button" onclick="start();">Continuar</button><br><br>&nbsp<button class="button" onclick="change('upload');">Enviar imagens</button><br>&nbsp</div><div id="bc"><h3>Banco de Questões</h3><button class="button" onclick="change('importar');;">Importar</button> <button class="button" onclick="change('exportar');;">Exportar</button><br>&nbsp</div><div id="warning"><h1>Aviso</h1><p>Você está com bloqueador de anuncios (adblock) ativo.</p><p>Esta aplicação não utiliza anuncios, porém os bloqueadores podem impedir seu correto funcionamento.</p><p>Por favor desative o adblock, se você não sabe como fazer isso clique <a href="https://veja.abril.com.br/como-desativar-adblock/">aqui</a>.</p><p>Se você estiver utilizando a aplicação por arquivo local, coloque <strong>"@@file:///$document"</strong> na lista de filtros</p></div></center></body><script type="text/javascript" src="js/script.js"></script><script type="text/javascript" src="js/change.js"></script></html>`)
		document.close
	}
	if (argument == 'importar') {
		document.open
		document.write(`<!DOCTYPE html><html><head><link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet"><link rel="stylesheet" type="text/css" href="css/style.css"><title>Banco de questões</title><meta charset="UTF-8"></head><body onload="resetad();"><center><div id="main1"><h1>Banco de questões - Importar</h1><label>Banco de Questões</label><br><input type="file" id="fileinput" onchange="changeFile();"><br><input type="text" id="xmltext" disabled="true"><br><label>Quantidade de questões</label><br><input type="number" name="q1" min="1" id="q1" value="1" required="true"><br><label>Quantidade de alternativas</label><br><input type="number" name="q2" min="2" id="q2" value="2" required="true"><br><label>Variedade de provas</label><br><input type="number" name="q3" min="1" id="q3" value="1" required="true"><br><label>Questões extras</label><br><input type="number" name="q4" min="0" id="q4" value="0" required="true"><br><br><button class="button" onclick="start();">Continuar</button><br><br>&nbsp<button class="button" onclick="change('upload');">Enviar imagens</button><br>&nbsp</div><div id="warning"><h1>Aviso</h1><p>Você está com bloqueador de anuncios (adblock) ativo.</p><p>Esta aplicação não utiliza anuncios, porém os bloqueadores podem impedir seu correto funcionamento.</p><p>Por favor desative o adblock, se você não sabe como fazer isso clique <a href="https://veja.abril.com.br/como-desativar-adblock/">aqui</a>.</p><p>Se você estiver utilizando a aplicação por arquivo local, coloque <strong>"@@file:///$document"</strong> na lista de filtros</p></div></center></body><script type="text/javascript" src="js/importar.js"></script><script type="text/javascript" src="js/change.js"></script><script type="text/javascript" src="js/xmlToJson.js"></script><script src="https://code.jquery.com/jquery-3.2.1.min.js"></script></html>`)
		document.close
	}
	if (argument == 'exportar') {
		
		document.write(`<!DOCTYPE html><html><head><link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet"><link rel="stylesheet" type="text/css" href="css/style.css"><title>Banco de questões</title><meta charset="UTF-8"></head><body onload="resetad();"><center><div id="main1"><h1>Banco de questões - Gerador</h1><label>Quantidade de questões</label><br><input type="number" name="q1" min="1" id="q1" value="1" required="true"><br><label>Quantidade de alternativas</label><br><input type="number" name="q2" min="2" id="q2" value="2" required="true"><br><br><button class="button" onclick="start();">Continuar</button><br><br>&nbsp<button class="button" onclick="change('upload');">Enviar imagens</button><br>&nbsp</div><div id="warning"><h1>Aviso</h1><p>Você está com bloqueador de anuncios (adblock) ativo.</p><p>Esta aplicação não utiliza anuncios, porém os bloqueadores podem impedir seu correto funcionamento.</p><p>Por favor desative o adblock, se você não sabe como fazer isso clique <a href="https://veja.abril.com.br/como-desativar-adblock/">aqui</a>.</p><p>Se você estiver utilizando a aplicação por arquivo local, coloque <strong>"@@file:///$document"</strong> na lista de filtros</p></div></center></body><script type="text/javascript" src="js/exportar.js"></script><script type="text/javascript" src="js/change.js"></script></html>`)
		
	}
	if (argument == 'upload') {
		
		document.write('<!DOCTYPE html><html><head> <meta charset="UTF-8"> <title>GP - Envio de Imagens</title> <meta name="viewport" content="width=device-width, initial-scale=1.0"> <link href="./css/upload.css" rel="stylesheet" media="screen"> <link href="./css/mobile-style.css" rel="stylesheet" media="screen"> <link rel="stylesheet" type="text/css" href="css/style.css"> <link rel="shortcut icon" href="./favicon.png"></head><body> <center> <div id="mainupload"> <div class="title"> <h1>Envio de imagem</h1> <p>Arraste a imagem para a zona pontilhada ou clique nela para adicionar o arquivo.</p></div><div class="dropzone"> <div class="info"></div></div><br>&nbsp</div></center> <script type="text/javascript" src="./js/imgur.js"></script> <script type="text/javascript" src="./js/upload.js"></script> <script type="text/javascript" src="./js/change.js"></script></body></html>')
		
	}
}